name: surgical-action-recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - pillow
  - opencv
  - pip
  - pip:
      - synapseclient
      - synapseutils
      - requests
